### ISSUE TITLE
Won't work at all in a live app

### ISSUE THREAD

**Issue by jeghers** [Gurpreets/react-gauge-capacity#1]
Never re-renders to display the value unless it is hard coded and never changes.  How can this ever be used in a real app then?

**Comment by Gurpreets** [comment]
Hi Jeghers,

In order to get scale on the gauge meter, one has to supply a set of dataset inputs (every time to get the different results) to this component as I have shown in the example. I hope this is the answer to your question.

Thanks
Gurpreet Singh

**Comment by jeghers** [comment]
I was doing that but still did not work

**Comment by Gurpreets** [comment]
@jeghers  If the issue still persists at your end. Could you please share that piece of code, where you have implemented it?
