### ISSUE TITLE
Component doesn't re-render arrow if arrow value changes.

### ISSUE THREAD

**Issue by brianunlam** [Gurpreets/react-gauge-capacity#3]
**Describe the bug**
When the arrowValue changes the arrow doesn't change.
**To Reproduce**
1. Change arrowValue in options.
2. The arrow doesn't change.

**Expected behavior**
The arrow must move if props change.

I could change the behavior and use it by modifying this line in render function:

-var gaugeArrowValue = this.state.arrowValue;
+var gaugeArrowValue = this.props.arrowValue;
	

Thanks.

**Comment by Gurpreets** [comment]
Thank you @brianunlam for notifying the issue. I will look into it.

**Comment by Gurpreets** [comment]
@brianunlam  It is fixed under version 2.0.1. Thank you.
